# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a8e97b10ba3bd57c3bd40e9f2ff92986d6123d1f474384575630220ded5b5863ee1475af0aa302438f41909d40aa2ce36fc949b2c02b65db6ee69bcd0fec215

test:
  secret_key_base: 8e3972a6604bb9ab6ca3ffb878ac7fa1f716604fb2c80fa82e5fbfbb3060dadb2b656d2b65985bc839ecb807a335c463571263aab5c0b3e8593cf77da115ead2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
